<a href="https://colab.research.google.com/github/Ankita-Singh05/Python/blob/main/Feb_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.array([1,2])

In [4]:
a

array([1, 2])

In [12]:
a=np.array([1,2,3,4])

In [7]:
a+2

array([3, 4, 5])

In [8]:
a-1

array([0, 1, 2])

In [9]:
a *2

array([2, 4, 6])

In [10]:
a/2

array([0.5, 1. , 1.5])

In [13]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [14]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
 a

array([1, 2, 3, 4])

In [16]:
b

array([1, 0, 1, 0])

In [17]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [18]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])