<a href="https://colab.research.google.com/github/Ankita-Singh05/Python/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello world")

Hello world


In [4]:
if(5>2):
  print (" 5 is greater")

 5 is greater


In [5]:
import numpy as np
import sys

In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [7]:
a*b

array([ 4, 10, 18])

In [8]:
a = [1,2,3]
b = [4,5,6]

In [9]:
a*b --> error

TypeError: ignored

In [34]:
c = np.array([1,3,5], dtype='int16')
c

array([1, 3, 5], dtype=int16)

In [11]:
print(c)

[1 3 5]


In [13]:
d = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
print(d)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
c.ndim

1

In [17]:
d.ndim

2

In [20]:
e = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]],[[10,11,12],[1,2,3]]])
print(e)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [ 1  2  3]]]


In [21]:
e.ndim

3

In [22]:
e.shape

(3, 2, 3)

In [23]:
d.shape

(2, 3)

In [24]:
c.shape

(3,)

In [25]:
r = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[4,5,6]])
r.ndim

2

In [26]:
r

array([[1., 2., 3.],
       [4., 5., 6.],
       [4., 5., 6.]])

In [27]:
c.dtype

dtype('int64')

In [30]:
d.dtype


dtype('int64')

In [31]:
e.dtype

dtype('int64')

In [35]:
c.dtype

dtype('int16')

In [36]:
c.itemsize

2

In [41]:
d.itemsize

8

In [39]:
c

array([1, 3, 5], dtype=int16)

In [42]:
c.size

3

In [43]:
c.size*c.itemsize

6

In [44]:
c.nbytes

6

# Accessing / Changing specific elements , rows, columns, etc

In [45]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [46]:
a.shape

(2, 7)

In [47]:
a.ndim

2

In [48]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [52]:
a[1,5]

13

In [53]:
a[1,-1]

14

In [54]:
a[1,-2]

13

In [55]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
a[:,1]

array([2, 9])

In [57]:
a[0,1:6:2]

array([2, 4, 6])

In [58]:
a[0,1:-2:2]

array([2, 4])

In [59]:
a[0,1:-1:2]

array([2, 4, 6])

In [60]:
a[1,5] = 22

In [61]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

In [62]:
a[:,2] =5

In [63]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 22, 14]])

In [64]:
a[:,2] = [3,10]

In [65]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 22, 14]])

## 3D EXAMPLE


In [69]:
a =  np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [70]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [71]:
b = np.array([[1,2,3],[3,4,5]])

In [72]:
b

array([[1, 2, 3],
       [3, 4, 5]])

In [73]:
a[1,1,1]

8

# Initializing different types of array

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [82]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [87]:
np.zeros((1,3,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [93]:
np.full((2,2),99, dtype ='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [104]:
np.full(c.shape,4)

array([4, 4, 4])

In [103]:
c

array([1, 3, 5], dtype=int16)

In [100]:
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [105]:
np.full_like(c,4)

array([4, 4, 4], dtype=int16)

In [107]:
np.random.rand(4,3,2)

array([[[0.64948543, 0.65357714],
        [0.32845812, 0.44067103],
        [0.43000834, 0.55713177]],

       [[0.18061627, 0.47742129],
        [0.31129981, 0.78010736],
        [0.2311933 , 0.27511001]],

       [[0.40292659, 0.55539136],
        [0.06155815, 0.91516501],
        [0.39568867, 0.12096069]],

       [[0.14241187, 0.73318417],
        [0.07613267, 0.88334155],
        [0.34137254, 0.68534352]]])

In [108]:
np.random.rand(a.shape)

TypeError: ignored

In [110]:
np.random.random_sample(c.shape)

array([0.68509749, 0.61568037, 0.78377625])

In [111]:
np.random.randint(7)

2

In [118]:
np.random.randint(5,10, size=(2,4))

array([[5, 7, 8, 8],
       [7, 5, 6, 5]])

In [119]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [121]:
arr = np.array([[1,2,3]])
repeatArr = np.repeat(arr,3,axis =0)

In [122]:
repeatArr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [123]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [128]:
test = np.ones((5,5), dtype='int32')
test

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [130]:
test[1:4,1:-1] =0

In [131]:
test

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [132]:
test[2,2]=9

In [133]:
test

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)